# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('parts', models.IntegerField(default=0)),
                ('manufacturingtime', models.TimeField()),
                ('idletime', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('settingtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Idle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idle_start', models.TimeField()),
                ('idle_stop', models.TimeField()),
                ('idle_diff', models.TimeField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Idle',
            },
        ),
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'MachineStatus',
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_start', models.TimeField()),
                ('run_stop', models.TimeField()),
                ('run_diff', models.TimeField()),
                ('date1', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Run',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sett_start', models.TimeField()),
                ('sett_stop', models.TimeField()),
                ('sett_diff', models.TimeField()),
                ('date2', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Setting',
            },
        ),
    ]
