# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_auto_20171208_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='idle',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='date1',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='date2',
            field=models.DateField(auto_now=True),
        ),
    ]
